### ISSUE TITLE
The type initializer for 'DotNetNuke.Modules.Blog.Data.DataProvider' threw an exception.

### ISSUE THREAD

**Issue by fireblind** [DNN-Connect/DNN-Blog#40]
Hey Guys,

I have installed versions 6.01.01, then removed it after experiencing this same error, then installed 6.01.02 and still get this error. There was no former versions of the module installed, and we are running DNN 7.04.01

It appears on page page load saying "A critical error has occurred. Please check the Event Viewer for further details." then upon checking the log I find this strange beast.

 at DotNetNuke.Modules.Blog.Security.ContextSecurity..ctor(Int32 moduleId, Int32 tabId, BlogInfo blog, UserInfo user)
   at DotNetNuke.Modules.Blog.Common.BlogContextInfo..ctor(HttpContext context, BlogModuleBase blogModule)
   at DotNetNuke.Modules.Blog.Common.BlogContextInfo.GetBlogContext(HttpContext& context, BlogModuleBase blogModule)
   at DotNetNuke.Modules.Blog.Common.BlogModuleBase.get_BlogContext()
   at DotNetNuke.Modules.Blog.Common.BlogModuleBase.AddBlogService()
   at DotNetNuke.Modules.Blog.Common.BlogModuleBase.Page_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by donker** [comment]
DotNetNuke.Modules.Blog.Data.DataProvider is responsible for "talking" to the SQL database. If it throws an error, one of the likely causes is that the database schema was not updated while the module was updated.

**Comment by Timo-Breumelhof** [comment]
I have the same issue with an upgraded version of the blog module

**Comment by Timo-Breumelhof** [comment]
When I run the SP on the DB and pass null for the locale, I don't get a return, when I pass 'NL-nl" an empty row.

EXEC	@return_value = [dbo].[Blog_GetBlogsByModule]
		@ModuleId = 9218,
		@UserId = 5,
		@Locale = 'en-us'

I guess for some reason the locale is not passed to the SP?

**Comment by Timo-Breumelhof** [comment]
I now uninstalled the module, removed any remaining stored-procedures in the database, deleted the files from the bin and desktop-modules folders an reinstalled the 6.1.1 version.
The error is gone, but the blog post are too.. :-(
Let's see if I manage without ruining the content... :-)

**Comment by Timo-Breumelhof** [comment]
For me it;s fixed. Looks like for some reason the old dlls were still in the bin folder and the other errors were from another module on the same page.

**Comment by donker** [comment]
It's due to a failed upgrade where the old dll was not deleted
