### ISSUE TITLE
Failure ExceptionSchwabenCode.QuickIO.UnmatchedFileSystemEntryTypeException: 

### ISSUE THREAD

**Issue by ErwinCraps** [DNN-Connect/DNN-Blog#96]
I get this errror when installing 06.04.01

Info Processing Cleanup File - 6.0.0
Failure ExceptionSchwabenCode.QuickIO.UnmatchedFileSystemEntryTypeException: FileSystemEntryType not matched!
 at SchwabenCode.QuickIO.QuickIOFile.InternalFileExists(String uncPath)
 at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFiles(Array arrPaths)
 at DotNetNuke.Services.Installer.Installers.CleanupInstaller.ProcessCleanupFile()
Info Completed Processing of Cleanup File - 6.0.0
Info Component installed successfully - Cleanup
Info Starting Installation - Cleanup
Info Processing Cleanup File - 6.0.4
Failure ExceptionSchwabenCode.QuickIO.UnmatchedFileSystemEntryTypeException: FileSystemEntryType not matched!
 at SchwabenCode.QuickIO.QuickIOFile.InternalFileExists(String uncPath)
 at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFiles(Array arrPaths)
 at DotNetNuke.Services.Installer.Installers.CleanupInstaller.ProcessCleanupFile()
Info Completed Processing of Cleanup File - 6.0.4

[Blog_06.04.01_Error.txt](https://github.com/DNN-Connect/DNN-Blog/files/795820/Blog_06.04.01_Error.txt)

**Comment by donker** [comment]
This is a DNN bug, not Blog bug. Apparently fixed in later versions of DNN.

**Comment by vincentparrett** [comment]
I just install on the latest dnn 9.1.1 and then blogd 6.04.01 and get the same error. Is there a work around for this?
